name: CI - Ruby

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      cache-key: rb-build
      run: bazel build //rb:selenium-devtools //rb:selenium-webdriver

  docs:
    name: Documentation
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Documentation
      cache-key: rb-docs
      run: bazel run //rb:docs

  lint:
    name: Lint
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Lint
      cache-key: rb-lint
      run: bazel run //rb:lint

  unit-tests:
    name: Unit Tests
    needs: build
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: 2.7.6
            os: ubuntu
          - ruby-version: 2.7.6
            os: windows
          - ruby-version: 3.2.0
            os: ubuntu
          - ruby-version: jruby-9.4.0.0
            os: ubuntu
          - ruby-version: truffleruby-22.3.0
            os: ubuntu
    with:
      name: Unit Tests (${{ matrix.ruby-version }}, ${{ matrix.os }})
      cache-key: rb-unit-test-${{ matrix.ruby-version }}
      os: ${{ matrix.os }}
      ruby-version: ${{ matrix.ruby-version }}
      run: bazel test --cache_test_results=no --test_output=all //rb:unit-test

  integration-tests-local:
    name: Integration Tests (Local)
    needs: build
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - edge
          - firefox
        os:
          - ubuntu
          - windows
        exclude:
          - browser: edge
            os: ubuntu
    with:
      name: Integration Tests (Local) (${{ matrix.browser }}, ${{ matrix.os }})
      browser: ${{ matrix.browser }}
      cache-key: rb-${{ matrix.browser }}-test
      os: ${{ matrix.os }}
      run: bazel test --cache_test_results=no --test_output=all //rb:${{ matrix.browser }}-test

  integration-tests-remote:
    name: Integration Tests (Remote)
    needs: build
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - edge
          - firefox
        os:
          - ubuntu
          - windows
        exclude:
          - browser: edge
            os: ubuntu
    with:
      name: Integration Tests (Remote) (${{ matrix.browser }}, ${{ matrix.os }})
      browser: ${{ matrix.browser }}
      cache-key: rb-${{ matrix.browser }}-test
      os: ${{ matrix.os }}
      run: bazel test --cache_test_results=no --test_output=all //rb:remote-${{ matrix.browser }}-test
