# Configuration for Ruby CI
# To force the execution of this workflow, add [run ruby] to your commit message
name: 'CI - Ruby'

on:
  workflow_dispatch:

  schedule:
    - cron: '35 9,21 * * *'

  push:

  pull_request:

jobs:
  check_workflow:
    permissions:
      contents: none
    uses: ./.github/workflows/should-workflow-run.yml
    with:
      bazel-target-prefix: '//rb'

  build:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[rb]') == true }}
    needs: check_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: gem
      - name: Build Webdriver Gem
        uses: ./.github/actions/bazel
        with:
          command: build //rb:selenium-webdriver
      - name: Build Devtools Gem
        uses: ./.github/actions/bazel
        with:
          command: build //rb:selenium-devtools

  chrome:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    needs: check_workflow
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu', 'windows', 'macos' ]
        version: [ 'stable' ]
        remote: [ '', 'remote-' ]
        include:
          - { "os": "ubuntu", "version": "beta", "browser": "chrome" }
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: ${{ matrix.remote }}chrome-test
      - name: Setup Fluxbox
        if: matrix.os == 'ubuntu'
        run: sudo apt-get -y install fluxbox
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.version }}
      - name: Start XVFB
        if: matrix.os == 'ubuntu'
        run: Xvfb :99 &
      - name: Start Fluxbox
        if: matrix.os == 'ubuntu'
        run: fluxbox -display :99 &
      - name: Set Windows resolution
        if: matrix.os == 'windows'
        run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
      - name: Set Mac resolution
        if: ${{ matrix.os == 'macos' }}
        run: |
          system_profiler SPDisplaysDataType | grep Resolution
          "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
          system_profiler SPDisplaysDataType | grep Resolution
      - name: Run Chrome tests
        uses: ./.github/actions/bazel
        with:
          command: test --cache_test_results=no --test_output=all //rb:${{ matrix.remote }}chrome-test
        env:
          DISPLAY: :99

  edge:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    needs: check_workflow
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows' ]
        browser: [ '', 'remote-' ]
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: edge-test
      - name: Setup Edge
        uses: browser-actions/setup-edge@latest
        with:
          edge-version: stable
      - name: Run Edge tests
        uses: ./.github/actions/bazel
        with:
          command: test --cache_test_results=no --test_output=all //rb:${{ matrix.remote }}edge-test

  ie:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    needs: check_workflow
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows' ]
        remote: [ '', 'remote-' ]
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: ${{ matrix.remote }}ie-test
      - name: Setup Edge
        uses: browser-actions/setup-edge@latest
        with:
          edge-version: stable
      - name: Run IE tests
        uses: ./.github/actions/bazel
        with:
          command: test --cache_test_results=no --test_output=all //rb:${{ matrix.remote }}ie-test

  firefox:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    needs: check_workflow
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu', 'windows' ]
        version: [ '' ]
        remote: [ '', 'remote-' ]
        include:
          - { "os": 'ubuntu', "version": "-devedition", "remote": "" }
          - { "os": 'windows', "version": "-devedition", "remote": "" }
          - { "os": 'macos', "version": "", "remote": "" }
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: ${{ matrix.remote }}firefox-test
      - name: Setup Fluxbox
        if: matrix.os == 'ubuntu'
        run: sudo apt-get -y install fluxbox
      - name: Setup Firefox
        uses: abhi1693/setup-browser@v0.3.5
        with:
          browser: firefox
          version: latest${{ matrix.version }}
      - name: Start XVFB
        if: matrix.os == 'ubuntu'
        run: Xvfb :99 &
      - name: Start Fluxbox
        if: matrix.os == 'ubuntu'
        run: fluxbox -display :99 &
      - name: Set Windows resolution
        if: matrix.os == 'windows'
        run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
      - name: Set Mac resolution
        if: ${{ matrix.os == 'macos' }}
        run: |
          system_profiler SPDisplaysDataType | grep Resolution
          "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
          system_profiler SPDisplaysDataType | grep Resolution
      - name: Run Firefox tests
        uses: ./.github/actions/bazel
        with:
          command: test --cache_test_results=no --test_output=all //rb:${{ matrix.remote }}firefox-test
        env:
          DISPLAY: :99

  docs:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    needs: check_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: docs
      - name: Run docs tests
        uses: ./.github/actions/bazel
        with:
          command: run //rb:docs

  lint:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    needs: check_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: lint
      - name: Run lint tests
        uses: ./.github/actions/bazel
        with:
          command: run //rb:lint

  unit-test:
    if: ${{ needs.check_workflow.outputs.result == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || contains(toJson(github.event.commits), '[run ruby]') == true }}
    needs: check_workflow
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7.6', '3.1.2', 'jruby-9.4.0.0', 'truffleruby-22.3.0' ]
        os: ['ubuntu-latest']
        include:
          - ruby: 2.7.6
            os: windows-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v3
      - name: Cache Bazel artifacts
        uses: ./.github/actions/cache-bazel
        with:
          workflow: ruby
          key: unit-test-${{ matrix.ruby }}
      - name: Set Ruby version to ${{ matrix.ruby }}
        run: echo 'RUBY_VERSION = "${{ matrix.ruby }}"' > rb/ruby_version.bzl
      - name: Run unit tests
        uses: ./.github/actions/bazel
        with:
          command: test --cache_test_results=no --test_output=all //rb:unit-test
